### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kolodziejczykjakub** [jakubkala/deep-learning-methods#4]
Implementacja wielowarstwowego perceptronu (MLP) uczonego
algorytmem propagacji wstecznej

- [x] Własnoręczna implementacja sieci, dozwolone jest użycie wyłącznie
podstawowych pakietów (NumPy, pandas, itp.) 

- [x] Liczba warstw i neuronów ukrytych w każdej warstwie

- [x] Funkcja aktywacji

- [x] Obecność biasu

- [x] Rozmiar batcha (Online vs batch learning)

- [x] Liczba iteracji

- [x] Wartość współczynnika nauki

- [x] Wartość współczynnika bezwładności

- [x] Rodzaj problemu: klasyfikacja lub regresja

 - [ ] Eksperymenty należy przeprowadzić na zbiorach danych
udostępnionych na pierwszych zajęciach

- [ ] Elementem oddania pierwszej części projektu jest nauczenie sieci na
zbiorach, które nie zostały wcześniej udostępnione

- [ ] Program powinien mieć możliwość zainicjowania powtarzalnego
procesu uczenia poprzez podania stałego ziarna generatora liczb
losowych

- [ ] Na wstępnym oddaniu projektu należy pokazać chociaż częściowo
przygotowany raport

- [ ] Elementy do zbadania:
➢ Wpływ funkcji aktywacji na skuteczność działania sieci – sprawdzić
funkcję sigmoidalną i dwie inne, dowolne funkcje aktywacji
wewnątrz sieci. Funkcja aktywacji na wyjściu musi być dobrana
odpowiednio do rodzaju problemu
➢ Wpływ liczby warstw ukrytych w sieci i ich liczności. Zbadać różne
liczby warstw od 0 do 4, kilka różnych architektur
➢ Wpływ funkcji błędu na wyjściu sieci na skuteczność uczenia.
Sprawdzić dwie funkcje błędu dla klasyfikacji i dwie dla regresji.

- [ ] Wymagania dotyczące aplikacji i oddania projektu:
➢ Aplikacja przetwarza zbiory zgodnie z podanym opisem
➢ Prezentuje w formie wykresu błąd sieci
na zbiorze uczącym i testowym
➢ Możliwość prześledzenia procesu uczenia
iteracja po iteracji (wizualizacja wag krawędzi)
➢ Wizualizacja błędu propagowanego w kolejnych
iteracjach uczenia (na każdej z wag)
➢ Wizualizacja zbioru uczącego oraz rezultatów klasyfikacji/regresji
➢ Student powinien umieć wyjaśnić przyczynę sukcesu lub porażki
danego modelu przy zadanych przez prowadzącego parametrach
sieci i zadania (możliwość sprawnej zmiany parametrów sieci oraz
zbiorów treningowych i testowych)

--------------------------------------------------------------------------------------------------------------------------------------

Druga część projektu polega na optymalizacji sieci w zadaniu
rozpoznawania cyfr (https://www.kaggle.com/c/digit-recognizer/)
➢ Uzyskany wynik powinien być zarejestrowany na platformie kaggle
- [ ] Raport powinien zawierać:
➢ Opis rozwiązywanego problemu, zrozumiały dla osoby, która nie
widziała treści zadania
➢ Opis zastosowanej sieci, jej działania oraz implementacji
➢ Opis przeprowadzonych eksperymentów
➢ Opracowane statystycznie wyniki (prezentowane w czytelny
sposób) oraz wnioski

--------------------------------------------------------------------------------------------------------------------------------------

Kilka luźnych myśli dotyczących raportu
➢ Czego nie ma w raporcie, tego nie było
➢ Raport jest dokumentem, należy zadbać o jego odpowiednią formę
(spis treści, bibliografia, podpisy pod rysunkami, tabelami, itp.)
➢ Wyniki powinny być opatrzone komentarzem
➢ Oprócz podawania średniej (np. accuracy), należy podawać również
odchylenie standardowe. Czasami gorsza średnia z małą wariancją
może okazać się bardziej pożądanym wynikiem niż nieco wyższa
średnia, ale z dużą wariancją
➢ Eksperymenty powinny być powtórzone wiele razy

--------------------------------------------------------------------------------------------------------------------------------------

Na ostateczne oddanie projektu składa się:
➢ Prezentacja programu prowadzącemu oraz odpowiedź na pytania
dotyczące jego działania
➢ Wysłanie prowadzącemu aplikacji (kodu) oraz raportu przed
rozpoczęciem zajęć
